name: Tarteeb Build Process
on:
  push: 
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Setup .Net
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0
        include-prerelease: true
    - name: Restore Packages
      run: dotnet restore
    - name: Build Projects
      run: dotnet build --no-restore
    - name: Run Tests
      run: dotnet test --no-build --verbosity normal
